import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    environment: 'jsdom',
    globals: true,
    include: ['src/**/*.test.ts'],
    coverage: {
      provider: 'v8',
      reporter: ['text', 'lcov'],
      include: ['src/**/*.ts'],
      exclude: [
        'src/**/*.test.ts',
        'src/**/*_types.ts',
        'src/**/*.d.ts',
        'src/main.ts',
        'src/index.ts',
        'src/**/constants.ts',
        'src/game/renderer*.ts',
        'src/game/ui*.ts',
        'src/game/main.ts',
        'src/admin.ts',
        'src/admin_config.ts',
        'src/admin_login.ts',
        'src/leaderboard.ts',
        'src/index_leaderboard.ts',
        'src/game/connection_ui.ts',
        'src/game/tutorial.ts',
        'src/game/waiting_tips.ts',
        'src/game/visual_helpers.ts',
        'src/shared/audio.ts',
        'src/shared/toast.ts',
        'src/shared/best_score_cookie.ts',
        'src/shared/tutorial_cookie.ts',
        'src/verify.ts',
        'src/game/restart_vote_ui.ts',
        'src/shared/types.ts',
        'src/game/state.ts',
        'src/game/websocket.ts',
      ],
      thresholds: {
        lines: 95,
        functions: 95,
        branches: 80,
        statements: 95,
      },
    },
  },
});
