package main

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type tsConst struct {
	path  string
	value string
}

func main() {
	outPath := "../../../frontend/src/shared/constants.ts"
	if len(os.Args) > 2 && os.Args[1] == "--out" {
		outPath = os.Args[2]
	}

	srcDir := "."
	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, srcDir, nil, parser.ParseComments)
	if err != nil {
		fmt.Fprintf(os.Stderr, "parse: %v\n", err)
		os.Exit(1)
	}

	pkg := pkgs["protocol"]
	if pkg == nil {
		fmt.Fprintf(os.Stderr, "package protocol not found\n")
		os.Exit(1)
	}

	var consts []tsConst
	seen := map[string]bool{}

	for _, f := range pkg.Files {
		for _, decl := range f.Decls {
			gen, ok := decl.(*ast.GenDecl)
			if !ok || gen.Tok != token.CONST {
				continue
			}

			var tsPath string
			if gen.Doc != nil {
				for _, c := range gen.Doc.List {
					if idx := strings.Index(c.Text, "@ts "); idx >= 0 {
						tsPath = strings.TrimSpace(c.Text[idx+4:])
					}
				}
			}

			for _, spec := range gen.Specs {
				vs, ok := spec.(*ast.ValueSpec)
				if !ok {
					continue
				}

				if vs.Doc != nil {
					for _, c := range vs.Doc.List {
						if idx := strings.Index(c.Text, "@ts "); idx >= 0 {
							tsPath = strings.TrimSpace(c.Text[idx+4:])
						}
					}
				}

				if tsPath == "" {
					continue
				}

				for _, valExpr := range vs.Values {
					val := exprValue(valExpr)
					if val == "" {
						continue
					}
					if !seen[tsPath] {
						consts = append(consts, tsConst{path: tsPath, value: val})
						seen[tsPath] = true
					}
				}
			}
		}
	}

	sort.Slice(consts, func(i, j int) bool {
		return consts[i].path < consts[j].path
	})

	physLines := []string{}
	cooldownLines := []string{}
	for _, c := range consts {
		key := c.path
		line := fmt.Sprintf("  %s: %s,", key[strings.Index(key, ".")+1:], c.value)
		if strings.HasPrefix(c.path, "PHYSICS.") {
			physLines = append(physLines, line)
		} else if strings.HasPrefix(c.path, "COOLDOWN.") {
			cooldownLines = append(cooldownLines, line)
		}
	}

	var sb strings.Builder
	sb.WriteString("// DO NOT EDIT — generated by go generate from backend/internal/protocol/constants.go\n\n")
	sb.WriteString("export const PHYSICS = {\n")
	for _, l := range physLines {
		sb.WriteString(l + "\n")
	}
	sb.WriteString("} as const;\n\n")
	sb.WriteString("export const COOLDOWN = {\n")
	for _, l := range cooldownLines {
		sb.WriteString(l + "\n")
	}
	sb.WriteString("} as const;\n")

	absPath := outPath
	if !filepath.IsAbs(absPath) {
		wd, _ := os.Getwd()
		absPath = filepath.Join(wd, absPath)
	}
	if err := os.WriteFile(absPath, []byte(sb.String()), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "write: %v\n", err)
		os.Exit(1)
	}
	fmt.Printf("generated %s\n", absPath)
}

func exprValue(expr ast.Expr) string {
	switch v := expr.(type) {
	case *ast.Ident:
		if v.Name == "TickRate" {
			return "15"
		}
		return ""
	case *ast.BasicLit:
		return v.Value
	case *ast.BinaryExpr:
		left := exprValue(v.X)
		right := exprValue(v.Y)
		if left == "" || right == "" {
			return ""
		}
		op := v.Op.String()
		if op == "/" && (left == "1000.0" || left == "1000") && (right == "float64(TickRate)" || right == "15") {
			return "1000 / 15"
		}
		if isFloat(left) || isFloat(right) {
			return fmt.Sprintf("%s %s %s", unFloat(left), op, unFloat(right))
		}
		return fmt.Sprintf("%s %s %s", left, op, right)
	case *ast.CallExpr:
		if len(v.Args) == 1 {
			arg := exprValue(v.Args[0])
			if arg != "" {
				return arg
			}
		}
		return ""
	case *ast.ParenExpr:
		inner := exprValue(v.X)
		if inner == "" {
			return ""
		}
		return "(" + inner + ")"
	default:
		return ""
	}
}

func isFloat(s string) bool {
	return strings.Contains(s, ".") || strings.HasPrefix(s, "float64")
}

func unFloat(s string) string {
	return strings.TrimPrefix(strings.TrimPrefix(s, "float64("), ")")
}
