package main

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

type tsConst struct {
	path  string
	value string
}

func main() {
	outPath := "../../../frontend/src/shared/game/constants.ts"
	if len(os.Args) > 2 && os.Args[1] == "--out" {
		outPath = os.Args[2]
	}

	content, err := generate(".")
	if err != nil {
		fmt.Fprintf(os.Stderr, "%v\n", err)
		os.Exit(1)
	}

	absPath := outPath
	if !filepath.IsAbs(absPath) {
		wd, _ := os.Getwd()
		absPath = filepath.Join(wd, absPath)
	}
	if err := os.WriteFile(absPath, []byte(content), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "write: %v\n", err)
		os.Exit(1)
	}
	fmt.Printf("generated %s\n", absPath)
}

// generate parses the Go package at srcDir, extracts all constants annotated
// with `@ts <path>` doc comments, and returns the TypeScript constants file
// content. It is a thin orchestrator over resolveConstValues → collectTSConsts
// → groupConsts → renderTS.
func generate(srcDir string) (string, error) {
	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, srcDir, nil, parser.ParseComments)
	if err != nil {
		return "", fmt.Errorf("parse: %w", err)
	}
	pkg := pkgs["protocol"]
	if pkg == nil {
		return "", fmt.Errorf("package protocol not found")
	}
	constValues := resolveConstValues(pkg)
	consts := collectTSConsts(pkg, constValues)
	groups, standalone := groupConsts(consts)
	return renderTS(groups, standalone), nil
}

// resolveConstValues builds a name→value map for ALL const identifiers so that
// expressions referencing other consts (e.g. TickInterval = 1000.0 / float64(TickRate))
// can be resolved without hardcoding values.
func resolveConstValues(pkg *ast.Package) map[string]string {
	constValues := map[string]string{}
	for _, f := range pkg.Files {
		for _, decl := range f.Decls {
			gen, ok := decl.(*ast.GenDecl)
			if !ok || gen.Tok != token.CONST {
				continue
			}
			for _, spec := range gen.Specs {
				vs, ok := spec.(*ast.ValueSpec)
				if !ok {
					continue
				}
				for i, name := range vs.Names {
					if i < len(vs.Values) {
						if val := exprValue(vs.Values[i], constValues); val != "" {
							constValues[name.Name] = val
						}
					}
				}
			}
		}
	}
	return constValues
}

// collectTSConsts extracts @ts-annotated consts for output, deduplicating by
// path and returning the slice sorted by path for deterministic output.
func collectTSConsts(pkg *ast.Package, constValues map[string]string) []tsConst {
	var consts []tsConst
	seen := map[string]bool{}
	for _, f := range pkg.Files {
		for _, decl := range f.Decls {
			gen, ok := decl.(*ast.GenDecl)
			if !ok || (gen.Tok != token.CONST && gen.Tok != token.VAR) {
				continue
			}

			var tsPath string
			if gen.Doc != nil {
				for _, c := range gen.Doc.List {
					if idx := strings.Index(c.Text, "@ts "); idx >= 0 {
						tsPath = strings.TrimSpace(c.Text[idx+4:])
					}
				}
			}

			for _, spec := range gen.Specs {
				vs, ok := spec.(*ast.ValueSpec)
				if !ok {
					continue
				}

				if vs.Doc != nil {
					for _, c := range vs.Doc.List {
						if idx := strings.Index(c.Text, "@ts "); idx >= 0 {
							tsPath = strings.TrimSpace(c.Text[idx+4:])
						}
					}
				}

				if tsPath == "" {
					continue
				}

				for _, valExpr := range vs.Values {
					val := exprValue(valExpr, constValues)
					if val == "" {
						continue
					}
					if !seen[tsPath] {
						consts = append(consts, tsConst{path: tsPath, value: val})
						seen[tsPath] = true
					}
				}
			}
		}
	}
	sort.Slice(consts, func(i, j int) bool {
		return consts[i].path < consts[j].path
	})
	return consts
}

// groupConsts splits consts into prefixed groups (e.g. "PHYSICS.") and
// standalone paths without a dot (e.g. "PALETTE_COLORS").
func groupConsts(consts []tsConst) (groups map[string][]tsConst, standalone []tsConst) {
	groups = map[string][]tsConst{}
	for _, c := range consts {
		idx := strings.Index(c.path, ".")
		if idx < 0 {
			standalone = append(standalone, c)
		} else {
			prefix := c.path[:idx]
			groups[prefix] = append(groups[prefix], c)
		}
	}
	return groups, standalone
}

// renderTS renders the TypeScript constants file content from grouped and
// standalone consts. Groups are emitted sorted by name; standalone consts
// follow in path order.
func renderTS(groups map[string][]tsConst, standalone []tsConst) string {
	var sb strings.Builder
	sb.WriteString("// DO NOT EDIT — generated by go generate from backend/internal/protocol/constants.go\n\n")

	groupNames := make([]string, 0, len(groups))
	for name := range groups {
		groupNames = append(groupNames, name)
	}
	sort.Strings(groupNames)

	for _, name := range groupNames {
		sb.WriteString(fmt.Sprintf("export const %s = {\n", name))
		for _, c := range groups[name] {
			key := c.path[strings.Index(c.path, ".")+1:]
			sb.WriteString(fmt.Sprintf("  %s: %s,\n", key, c.value))
		}
		sb.WriteString("} as const;\n\n")
	}

	for _, c := range standalone {
		sb.WriteString(fmt.Sprintf("export const %s = %s as const;\n", c.path, c.value))
	}

	return sb.String()
}

// exprValue evaluates an ast.Expr to its TypeScript literal representation.
// constValues maps Go const identifiers to their already-evaluated string
// values, so references like `TickRate` resolve to the actual source-of-truth
// value rather than a hardcoded magic number.
func exprValue(expr ast.Expr, constValues map[string]string) string {
	switch v := expr.(type) {
	case *ast.Ident:
		if val, ok := constValues[v.Name]; ok {
			return val
		}
		return ""
	case *ast.BasicLit:
		return v.Value
	case *ast.BinaryExpr:
		left := exprValue(v.X, constValues)
		right := exprValue(v.Y, constValues)
		if left == "" || right == "" {
			return ""
		}
		op := v.Op.String()
		if isFloat(left) || isFloat(right) {
			return fmt.Sprintf("%s %s %s", unFloat(left), op, unFloat(right))
		}
		return fmt.Sprintf("%s %s %s", left, op, right)
	case *ast.CallExpr:
		if len(v.Args) == 1 {
			arg := exprValue(v.Args[0], constValues)
			if arg != "" {
				return arg
			}
		}
		return ""
	case *ast.ParenExpr:
		inner := exprValue(v.X, constValues)
		if inner == "" {
			return ""
		}
		return "(" + inner + ")"
	case *ast.CompositeLit:
		return convertPaletteLit(v)
	default:
		return ""
	}
}

// convertPaletteLit converts a [N][3]uint8 composite literal (RGB triples)
// into a TypeScript array of '#rrggbb' hex strings. Returns "" for any other
// shape so that unsupported composite literals are skipped.
func convertPaletteLit(v *ast.CompositeLit) string {
	if len(v.Elts) == 0 {
		return ""
	}
	hexes := make([]string, 0, len(v.Elts))
	for _, elt := range v.Elts {
		inner, ok := elt.(*ast.CompositeLit)
		if !ok || len(inner.Elts) != 3 {
			return ""
		}
		r := decToUint(inner.Elts[0])
		g := decToUint(inner.Elts[1])
		b := decToUint(inner.Elts[2])
		if r < 0 || g < 0 || b < 0 {
			return ""
		}
		hexes = append(hexes, fmt.Sprintf("'#%02x%02x%02x'", r, g, b))
	}
	return "[" + strings.Join(hexes, ", ") + "]"
}

func decToUint(expr ast.Expr) int {
	switch v := expr.(type) {
	case *ast.BasicLit:
		n, err := strconv.Atoi(v.Value)
		if err != nil {
			return -1
		}
		return n
	case *ast.ParenExpr:
		return decToUint(v.X)
	default:
		return -1
	}
}

func isFloat(s string) bool {
	return strings.Contains(s, ".") || strings.HasPrefix(s, "float64")
}

func unFloat(s string) string {
	s = strings.TrimPrefix(s, "float64(")
	s = strings.TrimSuffix(s, ")")
	// Normalize integer-valued floats (e.g. 1000.0 → 1000) so the generated
	// TS uses clean integers where the Go source used a float literal.
	if strings.HasSuffix(s, ".0") {
		s = s[:len(s)-2]
	}
	return s
}
