//go:build ignore

// generate_nicknames reads shared/data/nicknames.json and emits Go + TS pool files.
// Run: go run scripts/codegen/generate_nicknames.go
package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

type nicknamesData struct {
	Adjectives []string            `json:"adjectives"`
	Categories map[string][]string `json:"categories"`
}

func main() {
	root := findRepoRoot()
	jsonPath := filepath.Join(root, "shared", "data", "nicknames.json")
	data, err := os.ReadFile(jsonPath)
	if err != nil {
		fatal(err)
	}
	var pools nicknamesData
	if err := json.Unmarshal(data, &pools); err != nil {
		fatal(err)
	}

	goOut := filepath.Join(root, "backend", "internal", "nicknames", "pools_gen.go")
	tsOut := filepath.Join(root, "frontend", "src", "shared", "assets", "nickname_pools_gen.ts")

	if err := os.WriteFile(goOut, renderGo(pools), 0o644); err != nil {
		fatal(err)
	}
	if err := os.WriteFile(tsOut, renderTS(pools), 0o644); err != nil {
		fatal(err)
	}
	fmt.Println("generated:", goOut)
	fmt.Println("generated:", tsOut)
}

func findRepoRoot() string {
	dir, err := os.Getwd()
	if err != nil {
		fatal(err)
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "shared", "data", "nicknames.json")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			fatal(fmt.Errorf("repo root not found"))
		}
		dir = parent
	}
}

func renderGo(p nicknamesData) []byte {
	var b bytes.Buffer
	b.WriteString("// Code generated by scripts/codegen/generate_nicknames.go; DO NOT EDIT.\n\n")
	b.WriteString("package nicknames\n\n")
	writeGoSlice(&b, "NicknameAdjectives", p.Adjectives)
	order := []struct{ key, varName string }{
		{"animals", "NicknameAnimals"},
		{"jobs", "NicknameJobs"},
		{"nature", "NicknameNature"},
		{"scifi", "NicknameScifi"},
	}
	for _, item := range order {
		writeGoSlice(&b, item.varName, p.Categories[item.key])
	}
	b.WriteString("// NicknameCategories contains all noun categories.\n")
	b.WriteString("var NicknameCategories = [][]string{\n")
	for _, item := range order {
		b.WriteString("\t" + item.varName + ",\n")
	}
	b.WriteString("}\n")
	return b.Bytes()
}

func writeGoSlice(b *bytes.Buffer, name string, items []string) {
	b.WriteString("var " + name + " = []string{\n")
	for i := 0; i < len(items); i += 8 {
		end := i + 8
		if end > len(items) {
			end = len(items)
		}
		chunk := items[i:end]
		quoted := make([]string, len(chunk))
		for j, s := range chunk {
			quoted[j] = fmt.Sprintf("%q", s)
		}
		b.WriteString("\t" + strings.Join(quoted, ", ") + ",\n")
	}
	b.WriteString("}\n\n")
}

func renderTS(p nicknamesData) []byte {
	var b bytes.Buffer
	b.WriteString("// Code generated by scripts/codegen/generate_nicknames.go; DO NOT EDIT.\n\n")
	writeTSSlice(&b, "NICKNAME_ADJECTIVES", p.Adjectives)
	order := []struct{ key, varName string }{
		{"animals", "NICKNAME_ANIMALS"},
		{"jobs", "NICKNAME_JOBS"},
		{"nature", "NICKNAME_NATURE"},
		{"scifi", "NICKNAME_SCIFI"},
	}
	for _, item := range order {
		writeTSSlice(&b, item.varName, p.Categories[item.key])
	}
	b.WriteString("export const NICKNAME_CATEGORIES: readonly (readonly string[])[] = [\n")
	for _, item := range order {
		b.WriteString("  " + item.varName + ",\n")
	}
	b.WriteString("] as const;\n")
	return b.Bytes()
}

func writeTSSlice(b *bytes.Buffer, name string, items []string) {
	b.WriteString("export const " + name + ": readonly string[] = [\n")
	for i := 0; i < len(items); i += 8 {
		end := i + 8
		if end > len(items) {
			end = len(items)
		}
		chunk := items[i:end]
		quoted := make([]string, len(chunk))
		for j, s := range chunk {
			quoted[j] = fmt.Sprintf("'%s'", s)
		}
		b.WriteString("  " + strings.Join(quoted, ", ") + ",\n")
	}
	b.WriteString("] as const;\n\n")
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
